### ISSUE TITLE
Is it possible to add the function of searching for custom keyword workflow?

### ISSUE THREAD

**Issue by touchmii** [Acidham/search-alfred-workflows#14]
some workflow use {var:keyword} as keyword.

**Comment by Acidham** [comment]
fixed in the latest release: https://github.com/Acidham/search-alfred-workflows/releases/tag/v2.3.5

**Comment by joedemcher** [comment]
Hello! 👋🏻 

I believe this may be an issue may need to be reopened. I am using the latest version (v2.3.8) downloaded from the Alfred Gallery and when I run the workflow all of my results only list the original/default keyword, not the one I selected during the configuration process.

For example, I use the [Emoji Wine](https://alfred.app/workflows/benjaminoddou/emoji-wine/) workflow, and in the configuration pane I changed the default `wine` keyword trigger to `emoji` before I installed it and yet `alf` still lists `wine` instead of `emoji`.

<img width="855" alt="Screenshot 2024-06-13 at 11 21 16 PM" src="https://github.com/Acidham/search-alfred-workflows/assets/23080198/f6fa6017-e31d-4ab9-bed2-ef05e855fb88">

<img width="828" alt="Screenshot 2024-06-13 at 11 21 45 PM" src="https://github.com/Acidham/search-alfred-workflows/assets/23080198/33011fff-5c85-4835-b55d-28dab5552e27">

<img width="817" alt="Screenshot 2024-06-13 at 11 21 54 PM" src="https://github.com/Acidham/search-alfred-workflows/assets/23080198/1ae1aebb-d538-4e88-bfb9-0bed9a5a6610">
